In [127]:
import pandas as pd

In [128]:
df=pd.read_csv("Train.csv")

In [129]:
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

Reduce size of dataset

In [130]:
df=df[0:10]

In [131]:
df.index=["Atharva", "Soham","Rahul","Mohit", "Vishwesh", "Rahul","Vineet","Ramesh","Mahesh","Shree"]

In [132]:
df

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
Atharva,1,D,Flight,4,2,177,3,low,F,44,1233,1
Soham,2,F,Flight,4,5,216,2,low,M,59,3088,1
Rahul,3,A,Flight,2,2,183,4,low,M,48,3374,1
Mohit,4,B,Flight,3,3,176,4,medium,M,10,1177,1
Vishwesh,5,C,Flight,2,2,184,3,medium,F,46,2484,1
Rahul,6,F,Flight,3,1,162,3,medium,F,12,1417,1
Vineet,7,D,Flight,3,4,250,3,low,F,3,2371,1
Ramesh,8,F,Flight,4,1,233,2,low,F,48,2804,1
Mahesh,9,A,Flight,3,4,150,3,low,F,11,1861,1
Shree,10,B,Flight,3,2,164,3,medium,F,29,1187,1

In [133]:
df.columns

Index(['ID', 'Warehouse_block', 'Mode_of_Shipment', 'Customer_care_calls',
       'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases',
       'Product_importance', 'Gender', 'Discount_offered', 'Weight_in_gms',
       'Reached.on.Time_Y.N'],
      dtype='object')

In [134]:
df.index

Index(['Atharva', 'Soham', 'Rahul', 'Mohit', 'Vishwesh', 'Rahul', 'Vineet',
       'Ramesh', 'Mahesh', 'Shree'],
      dtype='object')

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Atharva to Shree
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   10 non-null     int64
 1   Warehouse_block      10 non-null     object
 2   Mode_of_Shipment     10 non-null     object
 3   Customer_care_calls  10 non-null     int64
 4   Customer_rating      10 non-null     int64
 5   Cost_of_the_Product  10 non-null     int64
 6   Prior_purchases      10 non-null     int64
 7   Product_importance   10 non-null     object
 8   Gender               10 non-null     object
 9   Discount_offered     10 non-null     int64
 10  Weight_in_gms        10 non-null     int64
 11  Reached.on.Time_Y.N  10 non-null     int64
dtypes: int64(8), object(4)
memory usage: 1.0+ KB

In [136]:
df.size

120

In [137]:
df.describe()

,ID,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
count,10.00000,10.000000,10.000000,10.0000,10.000000,10.000000,10.000000,10.0
mean,5.50000,3.100000,2.600000,189.5000,3.000000,31.000000,2099.600000,1.0
std,3.02765,0.737865,1.349897,32.7151,0.666667,20.401525,835.100021,0.0
min,1.00000,2.000000,1.000000,150.0000,2.000000,3.000000,1177.000000,1.0
25%,3.25000,3.000000,2.000000,167.0000,3.000000,11.250000,1279.000000,1.0
50%,5.50000,3.000000,2.000000,180.0000,3.000000,36.500000,2116.000000,1.0
75%,7.75000,3.750000,3.750000,208.0000,3.000000,47.500000,2724.000000,1.0
max,10.00000,4.000000,5.000000,250.0000,4.000000,59.000000,3374.000000,1.0

In [138]:
df

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
Atharva,1,D,Flight,4,2,177,3,low,F,44,1233,1
Soham,2,F,Flight,4,5,216,2,low,M,59,3088,1
Rahul,3,A,Flight,2,2,183,4,low,M,48,3374,1
Mohit,4,B,Flight,3,3,176,4,medium,M,10,1177,1
Vishwesh,5,C,Flight,2,2,184,3,medium,F,46,2484,1
Rahul,6,F,Flight,3,1,162,3,medium,F,12,1417,1
Vineet,7,D,Flight,3,4,250,3,low,F,3,2371,1
Ramesh,8,F,Flight,4,1,233,2,low,F,48,2804,1
Mahesh,9,A,Flight,3,4,150,3,low,F,11,1861,1
Shree,10,B,Flight,3,2,164,3,medium,F,29,1187,1

In [139]:
df.loc["Atharva"]

ID                          1
Warehouse_block             D
Mode_of_Shipment       Flight
Customer_care_calls         4
Customer_rating             2
Cost_of_the_Product       177
Prior_purchases             3
Product_importance        low
Gender                      F
Discount_offered           44
Weight_in_gms            1233
Reached.on.Time_Y.N         1
Name: Atharva, dtype: object

In [140]:
df.iloc[0]

ID                          1
Warehouse_block             D
Mode_of_Shipment       Flight
Customer_care_calls         4
Customer_rating             2
Cost_of_the_Product       177
Prior_purchases             3
Product_importance        low
Gender                      F
Discount_offered           44
Weight_in_gms            1233
Reached.on.Time_Y.N         1
Name: Atharva, dtype: object

In [141]:
df.iloc[0].name="Riya"

In [142]:
df.loc["Atharva":"Mahesh", ["Gender", "Mode_of_Shipment"]]

         Gender Mode_of_Shipment
Atharva       F           Flight
Soham         M           Flight
Rahul         M           Flight
Mohit         M           Flight
Vishwesh      F           Flight
Rahul         F           Flight
Vineet        F           Flight
Ramesh        F           Flight
Mahesh        F           Flight

In [143]:
df.iloc[0:5, [3]]

          Customer_care_calls
Atharva                     4
Soham                       4
Rahul                       2
Mohit                       3
Vishwesh                    2

In [144]:
df.columns

Index(['ID', 'Warehouse_block', 'Mode_of_Shipment', 'Customer_care_calls',
       'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases',
       'Product_importance', 'Gender', 'Discount_offered', 'Weight_in_gms',
       'Reached.on.Time_Y.N'],
      dtype='object')

In [145]:
df[df["Prior_purchases"]==3]

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
Atharva,1,D,Flight,4,2,177,3,low,F,44,1233,1
Vishwesh,5,C,Flight,2,2,184,3,medium,F,46,2484,1
Rahul,6,F,Flight,3,1,162,3,medium,F,12,1417,1
Vineet,7,D,Flight,3,4,250,3,low,F,3,2371,1
Mahesh,9,A,Flight,3,4,150,3,low,F,11,1861,1
Shree,10,B,Flight,3,2,164,3,medium,F,29,1187,1

Dropping stuff

In [73]:
df

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
Soham,2,F,Flight,4,5,216,2,low,M,59,3088,1
Rahul,3,A,Flight,2,2,183,4,low,M,48,3374,1
Mohit,4,B,Flight,3,3,176,4,medium,M,10,1177,1
Vishwesh,5,C,Flight,2,2,184,3,medium,F,46,2484,1
Rahul,6,F,Flight,3,1,162,3,medium,F,12,1417,1
Vineet,7,D,Flight,3,4,250,3,low,F,3,2371,1
Ramesh,8,F,Flight,4,1,233,2,low,F,48,2804,1
Mahesh,9,A,Flight,3,4,150,3,low,F,11,1861,1
Shree,10,B,Flight,3,2,164,3,medium,F,29,1187,1

In [146]:
df

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
Atharva,1,D,Flight,4,2,177,3,low,F,44,1233,1
Soham,2,F,Flight,4,5,216,2,low,M,59,3088,1
Rahul,3,A,Flight,2,2,183,4,low,M,48,3374,1
Mohit,4,B,Flight,3,3,176,4,medium,M,10,1177,1
Vishwesh,5,C,Flight,2,2,184,3,medium,F,46,2484,1
Rahul,6,F,Flight,3,1,162,3,medium,F,12,1417,1
Vineet,7,D,Flight,3,4,250,3,low,F,3,2371,1
Ramesh,8,F,Flight,4,1,233,2,low,F,48,2804,1
Mahesh,9,A,Flight,3,4,150,3,low,F,11,1861,1
Shree,10,B,Flight,3,2,164,3,medium,F,29,1187,1

In [147]:
#dropping rows
df.drop("Atharva", axis=0)
#Note: df is not changed.
#To change df, run df=df.drop("Atharva")

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
Soham,2,F,Flight,4,5,216,2,low,M,59,3088,1
Rahul,3,A,Flight,2,2,183,4,low,M,48,3374,1
Mohit,4,B,Flight,3,3,176,4,medium,M,10,1177,1
Vishwesh,5,C,Flight,2,2,184,3,medium,F,46,2484,1
Rahul,6,F,Flight,3,1,162,3,medium,F,12,1417,1
Vineet,7,D,Flight,3,4,250,3,low,F,3,2371,1
Ramesh,8,F,Flight,4,1,233,2,low,F,48,2804,1
Mahesh,9,A,Flight,3,4,150,3,low,F,11,1861,1
Shree,10,B,Flight,3,2,164,3,medium,F,29,1187,1

In [148]:
#dropping columns
df.drop("ID", axis=1)

,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
Atharva,D,Flight,4,2,177,3,low,F,44,1233,1
Soham,F,Flight,4,5,216,2,low,M,59,3088,1
Rahul,A,Flight,2,2,183,4,low,M,48,3374,1
Mohit,B,Flight,3,3,176,4,medium,M,10,1177,1
Vishwesh,C,Flight,2,2,184,3,medium,F,46,2484,1
Rahul,F,Flight,3,1,162,3,medium,F,12,1417,1
Vineet,D,Flight,3,4,250,3,low,F,3,2371,1
Ramesh,F,Flight,4,1,233,2,low,F,48,2804,1
Mahesh,A,Flight,3,4,150,3,low,F,11,1861,1
Shree,B,Flight,3,2,164,3,medium,F,29,1187,1

In [149]:
df.columns

Index(['ID', 'Warehouse_block', 'Mode_of_Shipment', 'Customer_care_calls',
       'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases',
       'Product_importance', 'Gender', 'Discount_offered', 'Weight_in_gms',
       'Reached.on.Time_Y.N'],
      dtype='object')

In [150]:
df.drop(['ID', 'Warehouse_block','Mode_of_Shipment','Gender'], axis=1)

,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
Atharva,4,2,177,3,low,44,1233,1
Soham,4,5,216,2,low,59,3088,1
Rahul,2,2,183,4,low,48,3374,1
Mohit,3,3,176,4,medium,10,1177,1
Vishwesh,2,2,184,3,medium,46,2484,1
Rahul,3,1,162,3,medium,12,1417,1
Vineet,3,4,250,3,low,3,2371,1
Ramesh,4,1,233,2,low,48,2804,1
Mahesh,3,4,150,3,low,11,1861,1
Shree,3,2,164,3,medium,29,1187,1

In [153]:
df['Gender'] = df['Gender'].map({'F': 0, 'M': 1})

In [154]:
df["Gender"]

Atharva    NaN
Soham      NaN
Rahul      NaN
Mohit      NaN
Vishwesh   NaN
Rahul      NaN
Vineet     NaN
Ramesh     NaN
Mahesh     NaN
Shree      NaN
Name: Gender, dtype: float64